#!/bin/bash

# NGROK SETUP FOR NFC-SMT4 PROJECT
# ===============================

echo "=== NGROK HTTPS SETUP ==="
echo ""
echo "1. Pastikan ngrok sudah terinstall"
echo "   Jika belum: brew install ngrok (macOS)"
echo ""
echo "2. Auth ngrok (jika punya account):"
echo "   ngrok config add-authtoken YOUR_TOKEN"
echo ""
echo "3. Start Laravel server di port 8000:"
echo "   php artisan serve --port=8000"
echo ""
echo "4. Di terminal lain, jalankan ngrok:"
echo "   ngrok http 8000"
echo ""
echo "5. Copy URL HTTPS dari ngrok, contoh:"
echo "   https://abcd-1234.ngrok-free.app"
echo ""
echo "6. Update .env:"
echo "   APP_URL=https://abcd-1234.ngrok-free.app"
echo ""
echo "7. Jangan lupa tambahkan SANCTUM_STATEFUL_DOMAINS jika pakai API:"
echo "   SANCTUM_STATEFUL_DOMAINS=abcd-1234.ngrok-free.app"
echo ""
echo ""
echo "=== TESTING DARI HP ==="
echo ""
echo "1. Pastikan HP dan laptop di internet yang sama (tidak perlu WiFi sama)"
echo "2. Buka URL HTTPS ngrok di browser HP"
echo "3. Untuk NFC: Android Chrome 89+"
echo "4. Untuk QR: iOS Safari / Chrome iOS"
echo ""
